realm_id = 1403
client_id = "4b0ececf9c4248e5be5296669b39adda"
client_secret = "3GBM4ZkzwsPsoC6mNxMfbuGlx4O3f2Dm"
data_dir = "./data"
delay_mins = 5

save_flexbuffer = false
db_host = "127.0.0.1"
db_schema = "wow_auctions"
